/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as EndpointMonitorsIdRouteImport } from "./routes/endpoint-monitors.$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointMonitorsIdRoute = EndpointMonitorsIdRouteImport.update({
  id: "/endpoint-monitors/$id",
  path: "/endpoint-monitors/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/endpoint-monitors/$id": typeof EndpointMonitorsIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/endpoint-monitors/$id": typeof EndpointMonitorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/endpoint-monitors/$id": typeof EndpointMonitorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/endpoint-monitors/$id"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/endpoint-monitors/$id"
  id: "__root__" | "/" | "/endpoint-monitors/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndpointMonitorsIdRoute: typeof EndpointMonitorsIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/endpoint-monitors/$id": {
      id: "/endpoint-monitors/$id"
      path: "/endpoint-monitors/$id"
      fullPath: "/endpoint-monitors/$id"
      preLoaderRoute: typeof EndpointMonitorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndpointMonitorsIdRoute: EndpointMonitorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
